// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSe2QfzUMBwNpNriGNgMem9O-1Jo6eXbo',
    appId: '1:423875840483:web:a9c1f2715b26d0835378d6',
    messagingSenderId: '423875840483',
    projectId: 'fortunearrtlighting-365b4',
    authDomain: 'fortunearrtlighting-365b4.firebaseapp.com',
    databaseURL: 'https://fortunearrtlighting-365b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fortunearrtlighting-365b4.appspot.com',
    measurementId: 'G-Z68524HD0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL8OKMZXF4If-1LKzzHoU3ij220pRteV0',
    appId: '1:423875840483:android:a120f6e11c59ae725378d6',
    messagingSenderId: '423875840483',
    projectId: 'fortunearrtlighting-365b4',
    databaseURL: 'https://fortunearrtlighting-365b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fortunearrtlighting-365b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwe1eMW8LwPD3LG2MTe4qSQC4HVITb6FU',
    appId: '1:423875840483:ios:533b17a0f24def8c5378d6',
    messagingSenderId: '423875840483',
    projectId: 'fortunearrtlighting-365b4',
    databaseURL: 'https://fortunearrtlighting-365b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fortunearrtlighting-365b4.appspot.com',
    iosBundleId: 'com.example.fortunearrtlighting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwe1eMW8LwPD3LG2MTe4qSQC4HVITb6FU',
    appId: '1:423875840483:ios:533b17a0f24def8c5378d6',
    messagingSenderId: '423875840483',
    projectId: 'fortunearrtlighting-365b4',
    databaseURL: 'https://fortunearrtlighting-365b4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fortunearrtlighting-365b4.appspot.com',
    iosBundleId: 'com.example.fortunearrtlighting',
  );
}
